### ISSUE TITLE
Readiness Probe TCP Port should be 8000, 

### ISSUE THREAD

**Issue by ChrisHoban** [bcgov/jag-lcrb-carla-public#1334]
https://github.com/bcgov/jag-lcrb-carla-public/blob/2c65c447fd62cbaed188e34b79ef263b625d2326/openshift/other-templates/splunk/splunk-deploy.json#L206

...otherwise the pod keeps restarting from failed readiness probes

**Comment by GeorgeWalker** [comment]
Thanks for letting us know Chris, I will fix that.
